INSERT INTO burgers (burger_name, devoured) VALUES ('The Cauliflower’s Cumin From Inside the House Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Poutine on the Ritz Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Fifth Day of Christmas Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('The Glass Fromagerie Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('The Human Polenta-pede Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('I Know Why the Cajun Burger Sings', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Open Sesame Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Chile Relleno-You-Didn’t Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Top Butt Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('We’re Here, We’re Gruyere, Get Used to It Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Blondes Have More Fun-gus Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Never Been Feta', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Mission A-Corn-Plished Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Papaya Was a Rolling Stone Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Hit Me With Your Best Shallot Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Say It Ain’t Cilantro Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('She’s A Super Leek Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Not if I can Kelp it Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Runny Out of Time Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Pepper Dont Preach', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Rest in Peas Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('These Collards Dont Run Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Olive And Let Die Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('The Final Kraut Down Burger', false);
